# Dependencies
markdown:         kramdown
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Matin Afshar  
tagline:          'Personal Site'
description:      ''
url:              https://Matin-Afshar.github.io/

highlighter:      rouge
markdown:         kramdown

paginate:         5

github:
  repo:           https://github.com/mbarzegary/mbarzegary.github.io
